/*global systemDictionary:true */
'use strict';

systemDictionary = {
  'ford adapter settings': {
    en: 'Adapter settings for ford',
    de: 'Adaptereinstellungen für ford',
    ru: 'Настройки адаптера для ford',
    pt: 'Configurações do adaptador para ford',
    nl: 'Adapterinstellingen voor ford',
    fr: "Paramètres d'adaptateur pour ford",
    it: "Impostazioni dell'adattatore per ford",
    es: 'Ajustes del adaptador para ford',
    pl: 'Ustawienia adaptera dla ford',
    'zh-cn': 'ford的适配器设置',
  },
  'FordPass App Email': {
    en: 'FordPass App Username',
    de: 'FordPass App-Benutzername',
    ru: 'Имя пользователя приложения',
    pt: 'Nome de usuário do aplicativo',
    nl: 'App-gebruikersnaam',
    fr: "Nom d'utilisateur de l'application",
    it: "Nome utente dell'app",
    es: 'Nombre de usuario de la aplicación',
    pl: 'Nazwa użytkownika aplikacji',
    'zh-cn': '应用用户名',
  },
  'FordPass App Password': {
    en: 'FordPass App Password',
    de: 'FordPass App-Passwort',
    ru: 'Пароль приложения',
    pt: 'Senha de app',
    nl: 'App-wachtwoord',
    fr: "Mot de passe de l'application",
    it: "Password dell'app",
    es: 'Contraseña de la aplicación',
    pl: 'Hasło do aplikacji',
    'zh-cn': '应用密码',
  },
  'Update interval in minutes': {
    en: 'Update interval in minutes',
    de: 'Aktualisierungsintervall in Minuten',
    ru: 'Интервал обновления в минутах',
    pt: 'Intervalo de atualização em minutos',
    nl: 'Update-interval in minuten',
    fr: 'Intervalle de mise à jour en minutes',
    it: 'Intervallo di aggiornamento in minuti',
    es: 'Intervalo de actualización en minutos',
    pl: 'Interwał aktualizacji w minutach',
    'zh-cn': '以分钟为单位的更新间隔',
  },
};
